### ISSUE TITLE
Adding splash screen

### ISSUE THREAD

**Issue by strange98350** [VictorImm/grocery-list#2]
Please assign this issue to me ? @VictorImm 

I could not find the way to tag it with hacktoberfest. Kindly add it

**Comment by VictorImm** [comment]
sure!

**Comment by abhijha1** [comment]
assign me please

**Comment by VictorImm** [comment]
@strange98350 are you still in progress?

**Comment by PIYUSH-69** [comment]
Please assign this to me

**Comment by PIYUSH-69** [comment]
Can you state what kind of splash screen is required?

**Comment by PIYUSH-69** [comment]
@VictorImm Please check the #11 .I have added the required splash screen
