### ISSUE TITLE
Remove item from cart

### ISSUE THREAD

**Issue by HimanshuC22** [VictorImm/grocery-list#3]
There should be an option to remove item from cart

**Comment by VictorImm** [comment]
ok!

**Comment by HimanshuC22** [comment]
@VictorImm I have opened a PR for the same #4 . You can review, test and verify the changes.
![Screenshot_1696837143](https://github.com/VictorImm/grocery-list/assets/32409453/6b2555e0-43a2-4ebf-8b2a-24b2007d8d92)

**Comment by VictorImm** [comment]
can you make it into a new feature? for example delete by item name, but keep the checkbox so different widget, different functionality. because I see the adapter u changed, it just changed the widget from checkbox to imageButton

**Comment by HimanshuC22** [comment]
Didn't get you, can u explain it a bit? Currently I have added an ImageButton which is not visible on GroceryList but is visible in cart list. Do you want me to keep the checkbox in place of the ImageButton?

**Comment by VictorImm** [comment]
ooh i'm sorry, I thought you changed the main adapter (grocery_row)

**Comment by VictorImm** [comment]
Thank you!

**Comment by HimanshuC22** [comment]
Oh, No Problem. Check the PR and commits of there is any scope for improvement, or if it can be merged. Meanwhile I am looking for other improvements in the app.
