### ISSUE TITLE
Update readMe.md

### ISSUE THREAD

**Issue by VictorImm** [VictorImm/grocery-list#6]
Please be a little serious about this PR

Not accepted:
- "Hello World" update
- Spam update

**Comment by atraxia24** [comment]
Could you be a little more specific about what you want,  to be added to the readme?

**Comment by VictorImm** [comment]
How about the main purpose of this application, use case flow, and a snippet of UI application (but someone is still working about UI/UX)

p.s. : you can use ChatGPT

**Comment by atraxia24** [comment]
I am not acquainted with UI/UX at the moment. Also the link of the apk that you provided doesn't open and it redirects to this repo. So unless I know exactly what I am working on I can't really update the readme.

**Comment by VictorImm** [comment]
well, I'm not really sure when the UI/UX is finished. But, if you really want to make a hurry commit, feel free to do other details like the main purpose of this app
The .apk link still need to be considered whether it's important to add now or not (maybe deleted soon)

**Comment by atraxia24** [comment]
I'm sorry but I don't really understand the issue here. This is my first time so please help me out. Is this an application that is currently in the process of being created or is it one that has already been created? And if yes to the latter option, could you provide me with the link of it or guide me where I can find more information about it?

**Comment by PIYUSH-69** [comment]
can you assign me

**Comment by PIYUSH-69** [comment]
@VictorImm Can you please review the Read me Page . Have created a pull request already

**Comment by VictorImm** [comment]
okay, let me check

**Comment by VictorImm** [comment]
Thank you!
