### ISSUE TITLE
Bug Fixes 

### ISSUE THREAD

**Issue by Ismail-AD** [VictorImm/grocery-list#7]
I would like to address the following issues in application:

1.Prevent empty data submissions for categories.
2.Disallow quantity submissions of 0.
3.Resolve application crashes after a character limit is reached.

Please **ASSIGN** these issues to me, and I will ensure a Quick fix. Tag them with "HACKTOBERFEST" as well.
VIDEO FOR DEMO: 

https://github.com/VictorImm/grocery-list/assets/99780212/2aa6c818-42fc-421e-9097-27471b0cc992

**Comment by VictorImm** [comment]
Okay!

**Comment by VictorImm** [comment]
Thank you!
